### ISSUE TITLE
Signaltöne werden in der 1.0.289 nicht so ausgegeben wie beschrieben

### ISSUE THREAD

**Issue by HSchoch** [Ardumower/Sunray#118]
1 Signalton = Stopp, 
6 Signaltöne = Start, 
5 Signaltöne = Dock, 
3 Signaltöne = R / C-Modus EIN / AUS, 
9 Signaltöne = Herunterfahren

Beim Start kommt nur ein Ton, bei Stopp kein Ton, Beim Ausschalten kurze 2 Pipser

**Comment by holgerschochwitz** [comment]
Ist erledigt
