### ISSUE TITLE
Kartendatenformat GeoJSON verwenden

### ISSUE THREAD

**Issue by themanfrommoon** [Ardumower/Sunray#138]
Moin,

es kommt gelegentlich die Frage auf, ob man die Karte nicht mit einem Editor komfortabel editieren kann.
(Ich wollte eigentlich meine Karte in mein CAD System übernehmen, und habe deswegen nach einer Konvertierungsmöglichkeit gesucht. Dazu war meine Frage welches Datenformat die Karten haben. Leider haben sie aktuell kein genormtes Kartenformat. Aber ich bin bei meiner kurzen Recherche schnell auf ein passendes und perfekt geeignetes Kartenformat gestoßen: GeoJSON)
Da es für GeoJSON viele Editoren und Viewer gibt, ist das sicherlich die beste Variante, um nicht auch noch einen Editor programmieren zu müssen. Man kann einfach diesen Standard verwenden und so jede Menge 3rd Party Tools mitbenutzen.
Import, Export, Editor, alles dabei.
Die Daten sind auch untereinander kompatibel, d.h. man kann jeden Editor benutzen und die gleichen Daten benutzen.
https://de.wikipedia.org/wiki/GeoJSON
https://geojson.io/
https://vector.rocks/
https://geo-json.com/
https://mygeodata.cloud/map/
https://mygeodata.cloud/converter/ (mit diesem Konverter kann man auch .dxf Dateien erzeugen und dann im CAD laden)
![image](https://github.com/Ardumower/Sunray/assets/28815063/41438057-d933-4182-9b7f-baef62ea8a4f)

**Comment by greymfm** [comment]
Ist so umgesetzt worden (under Mapping-Menü "Map Data") :-)  Wenn nichts dagegen spricht können wir den Issue schliessen? :-)
