### ISSUE TITLE
error: no map route

### ISSUE THREAD

**Issue by jopl** [Ardumower/Sunray#14]
Dear ardumower sunray enthusiastics, I successfully built the ardumower sunray model with standalone RTK. Everything seems to be working during creating the map, but after map is created and calculated, the tracking lines appears in the map and system writes the error "no map route" and rover doesn't want to start mowing. Is it possible to have such issue due to I am using free license, please? And does it solve after purchase of new license? Or what other problem could be the reason for such error message?
Thank you for your answer in advance. Kind regards, jopl.

**Comment by greymfm** [comment]
Hello, we are not using GitHub as support forum (it's for discussing code), have you considered to ask in the forum? :-) 
https://forum.ardumower.de/forums/sunray-firmware.22006/
Also, you can find answers to most common user issues in the Wiki troubleshooting section ( https://wiki.ardumower.de/index.php?title=Ardumower_Sunray#Troubleshooting )

**Comment by jopl** [comment]
Dear Alex, of course, thank you. It is solved at the moment, the issue was too small test area ... when I use larger one, everything is OK. Thank you so much. Regards, Josef.
