### ISSUE TITLE
Clock config and Cache enabled

### ISSUE THREAD

**Issue by Viatorus** [Ardumower/Sunray#19]
I don't see any clock configuration or SAMD51 cache enable instructions inside the sources.

Why is that so? Did I missed it?
At what frequency runs the CPU?

**Comment by rweickelt** [comment]
> I don't see any clock configuration or SAMD51 cache enable instructions inside the sources.

The Arduino IDE sets the define `ENABLE_CACHE` and uses the startup code from `${ARDUINO_DATA_PATH}/packages/adafruit/hardware/samd/1.7.2/cores/arduino/startup.c`. Have a look at that file.

> At what frequency runs the CPU?

The Arduino IDE sets the define `F_CPU=120000000L`. Search for `F_CPU` in the very same file.

**Comment by Viatorus** [comment]
Ah, thank you! Just wanted to make sure it is not missed here. :)
