### ISSUE TITLE
path trackig going wrong sporadically (robot kidnaps itself)

### ISSUE THREAD

**Issue by greymfm** [Ardumower/Sunray#3]
Very sporadically (every few hours or so), the path tracking is going wrong. If it happens, the mower has good GPS signal (fix), but is driving completely away from the planned path...

The problem might be related to the path-tracking formula (stanley controller):

![grafik](https://user-images.githubusercontent.com/11735886/88968376-8aeb2f00-d2af-11ea-83ba-42e4d8ee6dc6.png)
https://medium.com/@dingyan7361/three-methods-of-vehicle-lateral-control-pure-pursuit-stanley-and-mpc-db8cc1d32081

Current workaround for this bug (this is NOT a bugfix): 
in config.h, activate :
`#define KIDNAP_DETECT true`
...so robot at least detects if being kidnapped (or is kidnapping itself) :-) (it will then go into ERROR mode)

Here you can see how the robot drives towards a not planned waypoint:
![Screenshot from 2020-09-29 13-20-48](https://user-images.githubusercontent.com/11735886/94552186-c629c000-0256-11eb-8a79-865af7ebd867.png)

**Comment by fracii** [comment]
Happened to my robot all the time when it was in fix mode but "Seconds" was pretty high.

**Comment by fracii** [comment]
Can verify your problem eaven now when I have Good Base and Rover setup with fix and 0.02s. Any info to get from the log, somehow I can help?

**Comment by greymfm** [comment]
Problem should be fixed in firmware v1.0.146 ...  :-)

**Comment by fracii** [comment]
Nice work Alexander! :) I going to put 4WD today ;)
