### ISSUE TITLE
Heat mapping (network coverage) of WLAN, GPS fix, GPS float, XBEE, etc.

### ISSUE THREAD

**Issue by themanfrommoon** [Ardumower/Sunray#39]
Create heat mapping (network coverage) of WLAN, GPS fix, GPS float, XBEE, etc. while mowing, i.e. measure network coverage and display it on the map. This is how you can find out blind areas and initiate improvement measures.

**Comment by greymfm** [comment]
Implemented as a Python-script (see folder 'https://github.com/Ardumower/Sunray/tree/master/heatmap' )
