### ISSUE TITLE
raspberry compile support

### ISSUE THREAD

**Issue by scube38** [Ardumower/Sunray#49]
Hi, trying to compile on raspbery(raspiarduino) and getting compilation errors:

sunray/src/raspi/raspi.h:6:25: fatal error: LinuxSerial.h: No such file or directory

did I wrongly supposed sunray code can run on raspberry with low level dive running on AGM4 via serial driver ?
Thanks

**Comment by greymfm** [comment]
yes, the Arduino library code base for Linux is not open-source (only used in-house), so Sunray will not compile on Linux.

**Comment by greymfm** [comment]
Fixed. Please see README ('How to compile 'Sunray for Alfred' on a Raspberry PI (OS Lite 64 bit, Debian Bullseye') for details.

**Comment by greymfm** [comment]
Fixed. Please see README ('How to compile 'Sunray for Alfred' on a Raspberry PI (OS Lite 64 bit, Debian Bullseye') for details.

**Comment by greymfm** [comment]
Fixed. Please see README ('How to compile 'Sunray for Alfred' on a Raspberry PI (OS Lite 64 bit, Debian Bullseye') for details.
