### ISSUE TITLE
Problem compiling

### ISSUE THREAD

**Issue by jonaslindemann** [Ardumower/Sunray#61]
Hi!

I get this when compiling version 1.0.230:

Sunray-1.0.230\sunray\src\mpu\inv_mpu.c:53:1: error: no return statement in function returning non-void [-Werror=return-type]

Seems to be related to an empty

static inline int reg_int_cb(struct int_param_s *int_param)
{
	
}

Thanks in advance.

**Comment by greymfm** [comment]
Hello, can you send me your config.h file? Looks like some definition from config_example.h might be missing in it...

**Comment by jonaslindemann** [comment]
Here it is:

https://www.dropbox.com/s/46jtpn81niaq9ue/config.h?dl=0

We have the standard Ardumower kit. Board 1.4

**Comment by greymfm** [comment]
Thanks, no issues (using your config.h) with compilation here. I'm on Arduino IDE 1.8.13. Which one did you try?

**Comment by jonaslindemann** [comment]
I downloaded the latest version, 1.8.19, perhaps I should have downloaded 1.8.13.

**Comment by jonaslindemann** [comment]
Problem solved. Used the wrong version of a library.
