### ISSUE TITLE
Current Motor calculation inverted

### ISSUE THREAD

**Issue by slide97** [Ardumower/Sunray#63]
Hi, 

in void AmMotorDriver::getMotorCurrent(float &leftCurrent, float &rightCurrent, float &mowCurrent) function 
the leftCurrent is based on the Right Sense pin and the right Current is based on the Left Sense pin :
      leftCurrent = (((float)ADC2voltage(analogRead(pinMotorRightSense))) + offset) *scale;
      rightCurrent = (((float)ADC2voltage(analogRead(pinMotorLeftSense))) + offset) *scale;
should be the opposite no ?
thanks

**Comment by greymfm** [comment]
Hi,
You are right! Actually, it doesn't make any difference in real mowing. Fixed it.
Thanks!
Alexander
