### ISSUE TITLE
Missing driver call in battery.cpp

### ISSUE THREAD

**Issue by hanoba** [Ardumower/Sunray#7]
Line 130 in battery.cpp
     if ((switchOffAllowedIdle) || (switchOffByOperator)) digitalWrite(pinBatterySwitch, LOW);
should read
     if ((switchOffAllowedIdle) || (switchOffByOperator)) batteryDriver.keepPowerOn(false);

**Comment by greymfm** [comment]
Excellent! Thank you! I have corrected it.

**Comment by greymfm** [comment]
should be fixed
