### ISSUE TITLE
No error if bumper stays permanently triggered

### ISSUE THREAD

**Issue by Svol0** [Ardumower/Sunray#73]
In case of continuously triggering the bumper sensor, e.g. sensor is mechanically stuck, the mower tries to avoid the supposed obstacle permanently.

Possible solution:
Monitor if the sensor stays continuously triggered and after an adjustable time is exceeded, the mower goes into error mode.

Add in config.h under line "#define BUMPER_DEADTIME":
`#define BUMPER_MAX_TRIGGER_TIME 30  // if bumpersensor stays permanent triggered mower will stop with bumper error (time in seconds; 0 = disabled)`

Add in robot.cpp under line "bool dockReasonRainTriggered = false;":
`unsigned long bumperStayActivTime = 0;    // duration, the bumper stays triggered`
`unsigned long lastCallBumperObstacle = 0; // last call for bumper.obstacle`

Change in robot.cpp:
`  if (BUMPER_ENABLE){`
`    if ( (millis() > linearMotionStartTime + BUMPER_DEADTIME) && (bumper.obstacle()) ){  `
`      CONSOLE.println("bumper obstacle!");    `
`      statMowBumperCounter++;`
`      triggerObstacle();    `
`      return true;`
`    }`
`  }`
to:
`  if (BUMPER_ENABLE){`
`    if ( (millis() > linearMotionStartTime + BUMPER_DEADTIME) && (bumper.obstacle()) ){  `
`      CONSOLE.println("bumper obstacle!");    `
`      statMowBumperCounter++;`
`      triggerObstacle();    `
`      return true;`
`    }`
`    // check if bumper stays triggered for a long time periode (maybe blocked)`
`    if (bumper.obstacle() && (BUMPER_MAX_TRIGGER_TIME > 0)){`
`      if ((abs(motor.linearSpeedSet) >= MOTOR_MIN_SPEED) || (abs(motor.angularSpeedSet) >= MOTOR_MIN_SPEED)) {    // if no movement, bumperStayActivTime paused`
`        bumperStayActivTime = bumperStayActivTime + (millis()-lastCallBumperObstacle);`
`      }`
`      if ((bumperStayActivTime) > (BUMPER_MAX_TRIGGER_TIME * 1000)){   // maximum trigger time reached -> set error`
`        if (stateOp != OP_ERROR){ `
`          stateSensor = SENS_BUMPER;`
`          CONSOLE.println("ERROR BUMPER BLOCKED");`
`          setOperation(OP_ERROR);`
`        }`
`      }`
`    } else bumperStayActivTime = 0;`
`    lastCallBumperObstacle  = millis();`
`  }`

regards
Sven

**Comment by stephwe** [comment]
A very good function, I would have needed it more often when tufts of grass get caught under the bumper.
Unfortunately, it cannot be used in the current Sunray version at the moment because Alexander is restructuring the entire code.

Maybe we should wait a bit and then adapt the code for the current Sunray version.
