### ISSUE TITLE
Mower undocks automatically at full charge after manual docking

### ISSUE THREAD

**Issue by Svol0** [Ardumower/Sunray#76]
If the setting DOCK_AUTO_START is activated and the mower is send during mowing action to the docking station manually (Dock button), the mower automatically starts mowing again if the battery is fully charged.
Normally the mower should only go on with mowing, if he was send automatically to the docking station in case of empty battery. If the mower is send manually or by rain sensor to the docking station, the mower should stay there until he gets the external start command.

I have recognised the issue in master V1.0.274.

regards,
Sven

**Comment by Svol0** [comment]
The problem also occurs in the 1.0.276 release.
If you send the mower to the charging station via DOCK, it drives out again automatically after the charging process has been completed. If the mower is sent to the charging station manually, it must not drive out again on its own.

If the rain sensor is triggered while mowing, the mower drives to the charging station and remains there when it is fully charged. Exactly how it should be.

regards,
Sven

**Comment by stephwe** [comment]
Problem tritt bei mir auch auf. Beim manuellen Docking und nicht fertig gemähtem Mähplan fährt der Mover nach Beendigung des Laden selbstständig wieder raus.
Dock durch Regensensor funktioniert und Mover bleibt bis zum manuellen Start in der Ladestation, auch bei Beendigung der Ladung.

**Comment by greymfm** [comment]
Sollte behoben sein ab v1.0.284  :-)

https://github.com/Ardumower/Sunray/commit/e68daddb4c201a90511387a4b535656d4e78a855

**Comment by Svol0** [comment]
Hallo @greymfm ,
ich konnte es heute testen und es funktioniert.
Vielen Dank.
Gruß Sven
